export interface ExtractedScene {
  /** Zero-based index matching ParsedScene.index */
  index: number;
  /** Raw scene heading from the parsed script, e.g. "INT. COFFEE SHOP - DAY" */
  heading: string;
  /** 2-5 word descriptive title generated by AI */
  title: string;
}

export interface ExtractionResult {
  /** All speaking characters found in the script, sorted A-Z */
  characters: string[];
  /** Scenes in order, each with an AI-generated title */
  scenes: ExtractedScene[];
  /** Number of chunks the script was split into (1 when under the token threshold) */
  chunksProcessed: number;
}

export interface ExtractionOptions {
  /**
   * OpenAI chat model to use.
   * Defaults to "gpt-4o-mini" — cheap, fast, and sufficient for structured extraction.
   */
  model?: string;
}
